Repository caxy/php-htmldiff, pull requests merged in 2021-01, with the labels that each got.

#93 PHP8 Compatibility
  .scrutinizer.yml
  composer.json
  lib/Caxy/HtmlDiff/HtmlDiff.php
  lib/Caxy/HtmlDiff/Match.php
  lib/Caxy/HtmlDiff/MatchingBlock.php
  phpcs.xml
  phpunit.xml.dist
  tests/Caxy/Tests/AbstractTest.php
  tests/Caxy/Tests/HtmlDiff/Functional/HTMLPurifierConfigTest.php
Labels: size/L

#95 Changelog for release v0.1.10
  .github_changelog_generator
  CHANGELOG.md
Labels: size/S

#97 Bugfix Adding class crippled HTML in selfclosing tags
  lib/Caxy/HtmlDiff/HtmlDiff.php
  tests/fixtures/HtmlDiff/new-paragraph-and-list.html
  tests/fixtures/HtmlDiff/override-4.html
  tests/fixtures/HtmlDiff/override-5.html
  tests/fixtures/HtmlDiff/override-8.html
Labels: size/M

#89 Added option to disable HTML purifier
  README.md
  lib/Caxy/HtmlDiff/AbstractDiff.php
  lib/Caxy/HtmlDiff/HtmlDiffConfig.php
  lib/Caxy/HtmlDiff/Table/TableDiff.php
Labels: size/M

#96 Ported ListDiff to DOMDocument
  README.md
  composer.json
  lib/Caxy/HtmlDiff/AbstractDiff.php
  lib/Caxy/HtmlDiff/HtmlDiff.php
  lib/Caxy/HtmlDiff/ListDiff.php
  lib/Caxy/HtmlDiff/ListDiff/DiffList.php
  lib/Caxy/HtmlDiff/ListDiff/DiffListItem.php
  lib/Caxy/HtmlDiff/ListDiffLines.php
  lib/Caxy/HtmlDiff/Operation.php
  tests/Caxy/Tests/AbstractTest.php
  tests/Caxy/Tests/HtmlDiff/Functional/HtmlDiffFunctionalTest.php
  tests/Caxy/Tests/HtmlDiff/Performance/PerformanceTest.php
  tests/fixtures/HtmlDiff/ICC-5136.html
  tests/fixtures/HtmlDiff/first-and-last.html
  tests/fixtures/HtmlDiff/new-paragraph-and-list.html
  tests/fixtures/HtmlDiff/override-2.html
  tests/fixtures/HtmlDiff/override-4.html
  tests/fixtures/HtmlDiff/override-5.html
  tests/fixtures/HtmlDiff/override-6.html
  tests/fixtures/HtmlDiff/simple-list.html
  tests/fixtures/Performance/paragraphs_expected.html
Labels: size/XXL
